### ISSUE TITLE
Core 모듈 제거

### ISSUE THREAD

**Issue by olivejua** [f-lab-edu/task-buddy#26]
## 배경
> core 모듈을 다른 분리 서버에서 의존하면 필요한 기능 외 모든 기능의 비즈니스 로직에 접근가능하게 되어 관리 범위가 커질 수 있음. 이부분을 제거하기 위해 core모듈에 있던 비즈니스 로직을 다른 서버에서 필요한 비즈니스 로직을 가지고 있도록 업데이트하고 기존 core 모듈은 제거함 

## todo 
- [x] core 모듈 제거
- [x] api 에 비즈니스 로직 추가
- [x] scheduler에 비즈니스 로직 추가
- [x] ApiResponse 제거 
- [ ] 통합테스트에 TestContainers 적용
